"""Plain-language PDF audit report (Stage 4).

Written for someone who is *not* the person who ran the scanner -- a team lead,
a client, a security reviewer. Every finding is explained in ordinary words,
with the technical snippet kept secondary.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.llm_remediation.schemas import AuditRemediationReport
from app.static_scanner.engine import ScanResult

_SEV_COLOR = {
    "CRITICAL": colors.HexColor("#c0392b"),
    "HIGH": colors.HexColor("#d35400"),
    "MEDIUM": colors.HexColor("#b7950b"),
    "LOW": colors.HexColor("#1f6f8b"),
}

_SEV_GUIDE = {
    "CRITICAL": "Fix before this code ships. Can lead to full system compromise.",
    "HIGH": "Fix as a priority. Can expose data or let an attacker run code.",
    "MEDIUM": "Worth fixing. A risky pattern that turns serious in the wrong context.",
    "LOW": "Minor. Clean up when convenient.",
}

_FRIENDLY_RISK = {
    "SEC-001": (
        "The program can be made to run whatever code an attacker supplies. "
        "This is one of the most serious flaws a Python application can have."
    ),
    "SEC-002": (
        "User input is placed directly into a database query, so an attacker "
        "could read, change, or delete data they should not be able to touch "
        "(SQL injection)."
    ),
    "SEC-003": (
        "A password, key, or token is written straight into the source code. "
        "Anyone who can see the code -- or its history in version control -- "
        "gets that secret."
    ),
    "SEC-004": (
        "The program rebuilds objects from untrusted data in a way that can "
        "execute code. A malicious file or payload could take over the process."
    ),
    "SEC-005": (
        "A shell command is assembled from untrusted input, so an attacker could "
        "attach their own commands to it (command injection)."
    ),
    "SEC-006": (
        "TLS certificate checking is turned off, so the connection is not actually "
        "secure -- someone on the network can read or change the traffic."
    ),
    "SEC-007": (
        "A weak or broken cryptographic primitive is in use (an outdated hash, ECB "
        "mode, or a non-secure random source for a secret). It can be forged or "
        "predicted."
    ),
    "SEC-008": (
        "A framework setting is unsafe for production -- debug mode, or accepting "
        "requests for any host / on any network interface. Debug mode in particular "
        "can expose a remote code-execution console."
    ),
    "SEC-009": (
        "The API accepts cross-origin requests from any website. Combined with "
        "credentials, any site a logged-in user visits can act as that user."
    ),
    "SEC-010": (
        "The program loads data from an untrusted file in a format that can carry "
        "executable code (marshal, an unsafe YAML loader, a pickled model file)."
    ),
}

_MAX_CODE_LINES = 40


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    s = {
        "title": ParagraphStyle(
            "t", parent=base["Title"], fontSize=22, spaceAfter=4, leading=26
        ),
        "subtitle": ParagraphStyle(
            "st", parent=base["Normal"], fontSize=10, textColor=colors.grey
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"], fontSize=14, spaceBefore=16, spaceAfter=6
        ),
        "h3": ParagraphStyle(
            "h3", parent=base["Heading3"], fontSize=11.5, spaceBefore=12, spaceAfter=3
        ),
        "body": ParagraphStyle(
            "b", parent=base["BodyText"], fontSize=10, leading=14, alignment=TA_LEFT
        ),
        "label": ParagraphStyle(
            "l", parent=base["BodyText"], fontSize=9, leading=13,
            textColor=colors.HexColor("#444444"),
        ),
        "code": ParagraphStyle(
            "c", parent=base["Code"], fontSize=7.6, leading=9.4,
            backColor=colors.HexColor("#f4f4f6"),
            borderColor=colors.HexColor("#dddddd"), borderWidth=0.5,
            borderPadding=5, spaceBefore=3, spaceAfter=3,
        ),
    }
    return s


def _clip_code(text: str) -> str:
    lines = (text or "").splitlines()
    if len(lines) <= _MAX_CODE_LINES:
        return text or ""
    return "\n".join(lines[:_MAX_CODE_LINES] + [f"... ({len(lines) - _MAX_CODE_LINES} more lines)"])


def _footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(20 * mm, 12 * mm, "Generated by Hybrid Code Auditor")
    canvas.drawRightString(190 * mm, 12 * mm, f"Page {doc.page}")
    canvas.restoreState()


def payload_from_scan(
    result: ScanResult,
    report: AuditRemediationReport | None,
) -> dict[str, Any]:
    """Shape a ScanResult (+ optional report) like the web service payload."""
    return {
        "files_scanned": result.files_scanned,
        "files_skipped": result.files_skipped,
        "counts": result.counts_by_severity(),
        "violations": [
            {
                "rule_id": v.rule_id,
                "severity": v.severity.value,
                "title": v.title,
                "message": v.message,
                "file_path": v.file_path,
                "line_number": v.line_number,
                "snippet": v.snippet,
            }
            for v in result.violations
        ],
        "report": report.model_dump() if report is not None else None,
        "llm_used": report is not None,
        "llm_error": None,
    }


def render_pdf(
    payload: dict[str, Any],
    out_path: str | Path,
    *,
    project_label: str = "Uploaded project",
) -> Path:
    st = _styles()
    story: list[Any] = []
    violations = payload.get("violations", [])
    counts = payload.get("counts", {})
    report = payload.get("report")
    remediations = {
        (r["rule_id"], r["file_path"], r["line_number"]): r
        for r in (report or {}).get("remediations", [])
    }

    # ---- cover -------------------------------------------------------------
    story.append(Paragraph("Code Security Audit Report", st["title"]))
    now = datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")
    story.append(Paragraph(f"{project_label} &nbsp;&bull;&nbsp; {now}", st["subtitle"]))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#dddddd")))
    story.append(Spacer(1, 12))

    story.append(Paragraph("What this is", st["h2"]))
    story.append(Paragraph(
        "An automatic review of the project's Python source. A local analyzer "
        "reads the code (it never runs it) and flags five classes of security "
        "problem. "
        + (
            "Each confirmed issue below also carries an AI-drafted fix and test "
            "&mdash; treat those as a starting point that a developer should review, "
            "not a guaranteed patch."
            if payload.get("llm_used") and not payload.get("llm_error")
            else "The AI remediation step was not run, so issues below are "
            "un-triaged and have no suggested fix."
        ),
        st["body"],
    ))

    # ---- summary --------------------------------------------------------
    story.append(Paragraph("Summary", st["h2"]))
    total = len(violations)
    headline = (
        f"{total} issue{'' if total == 1 else 's'} found across "
        f"{payload.get('files_scanned', 0)} Python file"
        f"{'' if payload.get('files_scanned', 0) == 1 else 's'}."
        if total
        else f"No issues found across {payload.get('files_scanned', 0)} Python files."
    )
    story.append(Paragraph(headline, st["body"]))
    story.append(Spacer(1, 6))

    rows = [["Severity", "Count", "What it means"]]
    styles_tbl = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for i, sev in enumerate(["CRITICAL", "HIGH", "MEDIUM", "LOW"], start=1):
        rows.append([sev, str(counts.get(sev, 0)), _SEV_GUIDE[sev]])
        styles_tbl.append(("TEXTCOLOR", (0, i), (0, i), _SEV_COLOR[sev]))
        styles_tbl.append(("FONTNAME", (0, i), (0, i), "Helvetica-Bold"))
    tbl = Table(rows, colWidths=[24 * mm, 16 * mm, 120 * mm])
    tbl.setStyle(TableStyle(styles_tbl))
    story.append(tbl)

    if payload.get("llm_error"):
        story.append(Spacer(1, 6))
        story.append(Paragraph(
            f"<b>Note:</b> the AI remediation step failed ({payload['llm_error']}). "
            "Findings are shown without suggested fixes.",
            st["label"],
        ))

    if not violations:
        story.append(Spacer(1, 16))
        story.append(Paragraph(
            "Nothing further to report. The scanned code is clean against rules "
            "SEC-001 through SEC-005.",
            st["body"],
        ))
        _build(out_path, story)
        return Path(out_path)

    # ---- findings -----------------------------------------------------
    story.append(PageBreak())
    story.append(Paragraph("Findings", st["h2"]))
    story.append(Paragraph(
        "Ordered most severe first. “Where” points to the file and line "
        "inside the uploaded project.",
        st["label"],
    ))

    for idx, v in enumerate(violations, start=1):
        sev = v["severity"]
        story.append(Paragraph(
            f'<font color="#{_SEV_COLOR[sev].hexval()[2:]}">'
            f"<b>{idx}. [{sev}] {v['title']}</b></font>",
            st["h3"],
        ))
        story.append(Paragraph(
            f"<b>Where:</b> {v['file_path']}, line {v['line_number']} "
            f"&nbsp;({v['rule_id']})",
            st["label"],
        ))
        story.append(Paragraph(
            f"<b>Plain-English risk:</b> "
            f"{_FRIENDLY_RISK.get(v['rule_id'], v['message'])}",
            st["body"],
        ))
        story.append(Paragraph(f"<b>Scanner detail:</b> {v['message']}", st["label"]))

        if v.get("snippet"):
            story.append(Paragraph("The code in question:", st["label"]))
            story.append(Preformatted(_clip_code(v["snippet"]), st["code"]))

        rem = remediations.get((v["rule_id"], v["file_path"], v["line_number"]))
        if rem:
            if not rem["is_exploitable"]:
                story.append(Paragraph(
                    f"<b>AI assessment:</b> likely a false positive. "
                    f"{rem['root_cause']}",
                    st["body"],
                ))
            else:
                if rem.get("root_cause"):
                    story.append(Paragraph(
                        f"<b>Why it matters here:</b> {rem['root_cause']}", st["body"]
                    ))
                if rem.get("patched_code", "").strip():
                    story.append(Paragraph("Suggested fix (review before applying):", st["label"]))
                    story.append(Preformatted(_clip_code(rem["patched_code"]), st["code"]))
                if rem.get("unit_test", "").strip():
                    story.append(Paragraph("How to confirm the fix:", st["label"]))
                    story.append(Preformatted(_clip_code(rem["unit_test"]), st["code"]))

        story.append(Spacer(1, 4))
        story.append(HRFlowable(width="100%", color=colors.HexColor("#eeeeee")))

    _build(out_path, story)
    return Path(out_path)


def _build(out_path: str | Path, story: list[Any]) -> None:
    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=20 * mm,
        title="Code Security Audit Report",
    )
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
